[package]
org = "wSO2"
name = "manage_tokens"
version = "0.1.0"

[build-options]
observabilityIncluded = true

[[dependency]]
org = "ballerinax"
name = "hubspot.marketing.transactional"
version = "0.1.0"
repository = "local"